name: 01 - Building Blocks Workflow
on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success Step
        run: |
            echo "This step is designed to Succeed."
            exit 0
      - name: Say Goodbye
        run: echo "Goodbye, World!"