name: 02 - workflow-events

on:
    schedule:
      - cron: '0 0 * * *' # Runs every day at midnight UTC
    push:
    workflow_dispatch:


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "The workflow was triggered by a ${{ github.event_name }} event."