name: 03 - Workdlow Runners

on:
    workflow_dispatch:

jobs:
    ubuntu-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Show the runner operating system
              run: |
                  echo "This job is running on an Ubuntu runner."
                  echo "Runner OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show the runner operating system
              shell: bash
              run: |
                  echo "This job is running on a Windows runner."      
                  echo "Runner OS: $RUNNER_OS"
    macos-echo:
        runs-on: macos-latest
        steps:
            - name: Show the runner operating system
              shell: bash
              run: |
                  echo "This job is running on a macOS runner."
                  echo "Runner OS: $RUNNER_OS"
        

